# Generated by Django 4.1 on 2023-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0005_alter_bookdetailpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetailpost',
            name='quote',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetailpost',
            name='description',
            field=models.CharField(help_text='A short descriptionof your book', max_length=1500),
        ),
    ]
