# Generated by Django 4.1 on 2023-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0006_bookdetailpost_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='description',
            field=models.CharField(help_text='A short description of your book', max_length=1500),
        ),
        migrations.AlterField(
            model_name='bookdetailpost',
            name='title',
            field=models.CharField(help_text='The name of your book', max_length=200, unique=True),
        ),
    ]
