# Generated by Django 4.1 on 2023-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0009_alter_bookdetailpost_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='status',
            field=models.IntegerField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published'),
        ),
    ]
