# Generated by Django 4.1 on 2023-05-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0010_alter_bookdetailpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=200),
        ),
    ]
