# Generated by Django 4.1 on 2023-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0011_alter_bookdetailpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='description',
            field=models.TextField(help_text='A short description of your book', max_length=1500),
        ),
    ]
