# Generated by Django 4.1 on 2023-05-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0012_alter_bookdetailpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='description',
            field=models.TextField(help_text='A short description of your book'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the personmaking a comment', max_length=200)),
                ('description', models.TextField(help_text='The comment made')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('comment', models.ForeignKey(help_text='Numberof comments in a post', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academic_journals_app.bookdetailpost')),
            ],
        ),
    ]
