# Generated by Django 4.2 on 2023-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0012_aboutheaders_aboutpage_contactus_editorialmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutheaders',
            name='header_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutheaders',
            name='header_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
