# Generated by Django 4.1 on 2023-05-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0014_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Numberof comments in a post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academic_journals_app.bookdetailpost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date created', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, help_text='The comment made', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the person making a comment', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person making a comment', max_length=200, null=True),
        ),
    ]
