# Generated by Django 4.1 on 2023-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0015_alter_comment_comment_alter_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailpost',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
