# Generated by Django 4.1 on 2023-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_journals_app', '0017_owner_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='owner_details',
            options={'verbose_name': 'Owner_Detail', 'verbose_name_plural': 'Owner_Details'},
        ),
    ]
